In [173]:
from numpy.random import randn as rn
import pandas as pd
import numpy as np

In [174]:
matrix_data=rn(5,4) # normal standard ditribution
np.random.seed(1) # constant dataset

In [355]:
sd=rn(4,4)
np.random.seed(1)
sd

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ],
       [ 0.3190391 , -0.24937038,  1.46210794, -2.06014071],
       [-0.3224172 , -0.38405435,  1.13376944, -1.09989127]])

In [348]:
matrix_data

array([[-0.22232814, -0.20075807,  0.18656139,  0.41005165],
       [ 0.19829972,  0.11900865, -0.67066229,  0.37756379],
       [ 0.12182127,  1.12948391,  1.19891788,  0.18515642],
       [-0.37528495, -0.63873041,  0.42349435,  0.07734007],
       [-0.34385368,  0.04359686, -0.62000084,  0.69803203]])

In [176]:
# convert array and martix into dataFrame

In [356]:
pd.DataFrame(matrix_data) # then we get the default indexes

0         1         2         3
0 -0.222328 -0.200758  0.186561  0.410052
1  0.198300  0.119009 -0.670662  0.377564
2  0.121821  1.129484  1.198918  0.185156
3 -0.375285 -0.638730  0.423494  0.077340
4 -0.343854  0.043597 -0.620001  0.698032

In [177]:
df=pd.DataFrame(matrix_data,index=[23,3,423,34,45],columns=['sd','we','er','we'])

In [178]:
df

sd        we        er        we
23  -0.222328 -0.200758  0.186561  0.410052
3    0.198300  0.119009 -0.670662  0.377564
423  0.121821  1.129484  1.198918  0.185156
34  -0.375285 -0.638730  0.423494  0.077340
45  -0.343854  0.043597 -0.620001  0.698032

In [179]:
df['sd']

23    -0.222328
3      0.198300
423    0.121821
34    -0.375285
45    -0.343854
Name: sd, dtype: float64

In [180]:
df[['sd','we']]

sd        we        we
23  -0.222328 -0.200758  0.410052
3    0.198300  0.119009  0.377564
423  0.121821  1.129484  0.185156
34  -0.375285 -0.638730  0.077340
45  -0.343854  0.043597  0.698032

In [181]:
df.iloc[0] # iloc always caontains default indexex but log contain given indexsx

sd   -0.222328
we   -0.200758
er    0.186561
we    0.410052
Name: 23, dtype: float64

In [182]:
df.iloc[1]

sd    0.198300
we    0.119009
er   -0.670662
we    0.377564
Name: 3, dtype: float64

In [183]:
df.loc[3]

sd    0.198300
we    0.119009
er   -0.670662
we    0.377564
Name: 3, dtype: float64

In [184]:
df.loc[34] # access by user given index

sd   -0.375285
we   -0.638730
er    0.423494
we    0.077340
Name: 34, dtype: float64

In [185]:
df=pd.DataFrame(matrix_data,index=[23,3,45,34,45],columns=['sd','we','er','we'])

In [186]:
df

sd        we        er        we
23 -0.222328 -0.200758  0.186561  0.410052
3   0.198300  0.119009 -0.670662  0.377564
45  0.121821  1.129484  1.198918  0.185156
34 -0.375285 -0.638730  0.423494  0.077340
45 -0.343854  0.043597 -0.620001  0.698032

In [187]:
df.loc[45] # it returns the names index

sd        we        er        we
45  0.121821  1.129484  1.198918  0.185156
45 -0.343854  0.043597 -0.620001  0.698032

In [188]:
df.iloc[2]

sd    0.121821
we    1.129484
er    1.198918
we    0.185156
Name: 45, dtype: float64

In [189]:
df

sd        we        er        we
23 -0.222328 -0.200758  0.186561  0.410052
3   0.198300  0.119009 -0.670662  0.377564
45  0.121821  1.129484  1.198918  0.185156
34 -0.375285 -0.638730  0.423494  0.077340
45 -0.343854  0.043597 -0.620001  0.698032

In [190]:
df.iloc[1:3][['sd','er']]

sd        er
3   0.198300 -0.670662
45  0.121821  1.198918

In [358]:
df.iloc[[1,2,3]]

level_0 index  Age  Height  Weight Professional
1        1     b   67      56       4      Teacher
2        2     c   88       7       5       Docter
3        3     d    1       2       3        Norse

In [360]:
df.iloc[[1,2]]['Age']

1    67
2    88
Name: Age, dtype: int32

In [359]:
df.iloc[[1,2],[1,2]]

index  Age
1     b   67
2     c   88

In [192]:
## row and columns intersection

In [193]:
df.iloc[[3,2,1],[1]] # before comma consider rows .after comma consider columns

we
34 -0.638730
45  1.129484
3   0.119009

In [367]:
df

level_0 index  Age  Height  Weight Professional
0        0     A   34       2       3      Student
1        1     b   67      56       4      Teacher
2        2     c   88       7       5       Docter
3        3     d    1       2       3        Norse

In [368]:
df.iloc[[1,2],[1,2]]

index  Age
1     b   67
2     c   88

In [369]:
df.loc[[3,45],['sd','er']] # 

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Int64Index([45], dtype='int64'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

In [370]:
df.iloc[[0,4],[0,3]]

IndexError: positional indexers are out-of-bounds

In [371]:
df.loc[[3,45],['sd','we']]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Int64Index([45], dtype='int64'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

In [372]:
df.loc[[23,45],['sd','we']]

KeyError: "None of [Int64Index([23, 45], dtype='int64')] are in the [index]"

In [373]:
df

level_0 index  Age  Height  Weight Professional
0        0     A   34       2       3      Student
1        1     b   67      56       4      Teacher
2        2     c   88       7       5       Docter
3        3     d    1       2       3        Norse

In [374]:
df.iloc[:,-1]

0    Student
1    Teacher
2     Docter
3      Norse
Name: Professional, dtype: object

In [201]:
df.loc[23:45,'sd':'er'] # consecutive location

KeyError: 'Cannot get right slice bound for non-unique label: 45'

In [202]:
data=rn(4,5)
df1=pd.DataFrame(data,index=[10,20,30,40],columns=["A",'B','C','D','E'])

In [203]:
data

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521]])

In [204]:
df1

A         B         C         D         E
10  1.624345 -0.611756 -0.528172 -1.072969  0.865408
20 -2.301539  1.744812 -0.761207  0.319039 -0.249370
30  1.462108 -2.060141 -0.322417 -0.384054  1.133769
40 -1.099891 -0.172428 -0.877858  0.042214  0.582815

In [205]:
df.iloc[0]

sd   -0.222328
we   -0.200758
er    0.186561
we    0.410052
Name: 23, dtype: float64

In [206]:
df1['new']=df1['A']+df1['B']
df1['New(Sum of both columns )']=df1["new"]

In [207]:
df1

A         B         C         D         E       new  \
10  1.624345 -0.611756 -0.528172 -1.072969  0.865408  1.012589   
20 -2.301539  1.744812 -0.761207  0.319039 -0.249370 -0.556727   
30  1.462108 -2.060141 -0.322417 -0.384054  1.133769 -0.598033   
40 -1.099891 -0.172428 -0.877858  0.042214  0.582815 -1.272319   

    New(Sum of both columns )  
10                   1.012589  
20                  -0.556727  
30                  -0.598033  
40                  -1.272319

In [208]:
# how to drop the ccolumns

In [209]:
df1.drop('A',axis=1,inplace=True) # default axis=0

In [210]:
df1

B         C         D         E       new  \
10 -0.611756 -0.528172 -1.072969  0.865408  1.012589   
20  1.744812 -0.761207  0.319039 -0.249370 -0.556727   
30 -2.060141 -0.322417 -0.384054  1.133769 -0.598033   
40 -0.172428 -0.877858  0.042214  0.582815 -1.272319   

    New(Sum of both columns )  
10                   1.012589  
20                  -0.556727  
30                  -0.598033  
40                  -1.272319

In [211]:
df1

B         C         D         E       new  \
10 -0.611756 -0.528172 -1.072969  0.865408  1.012589   
20  1.744812 -0.761207  0.319039 -0.249370 -0.556727   
30 -2.060141 -0.322417 -0.384054  1.133769 -0.598033   
40 -0.172428 -0.877858  0.042214  0.582815 -1.272319   

    New(Sum of both columns )  
10                   1.012589  
20                  -0.556727  
30                  -0.598033  
40                  -1.272319

In [212]:
df1.drop(10) # delete rows

B         C         D         E       new  \
20  1.744812 -0.761207  0.319039 -0.249370 -0.556727   
30 -2.060141 -0.322417 -0.384054  1.133769 -0.598033   
40 -0.172428 -0.877858  0.042214  0.582815 -1.272319   

    New(Sum of both columns )  
20                  -0.556727  
30                  -0.598033  
40                  -1.272319

In [213]:
df1.drop(0) # it does not consider the default index

KeyError: '[0] not found in axis'

In [214]:
df1.drop(10,inplace=True)

In [215]:
df1

B         C         D         E       new  \
20  1.744812 -0.761207  0.319039 -0.249370 -0.556727   
30 -2.060141 -0.322417 -0.384054  1.133769 -0.598033   
40 -0.172428 -0.877858  0.042214  0.582815 -1.272319   

    New(Sum of both columns )  
20                  -0.556727  
30                  -0.598033  
40                  -1.272319

In [216]:
df1

B         C         D         E       new  \
20  1.744812 -0.761207  0.319039 -0.249370 -0.556727   
30 -2.060141 -0.322417 -0.384054  1.133769 -0.598033   
40 -0.172428 -0.877858  0.042214  0.582815 -1.272319   

    New(Sum of both columns )  
20                  -0.556727  
30                  -0.598033  
40                  -1.272319

In [218]:
df1

B         C         D         E       new  \
20  1.744812 -0.761207  0.319039 -0.249370 -0.556727   
30 -2.060141 -0.322417 -0.384054  1.133769 -0.598033   
40 -0.172428 -0.877858  0.042214  0.582815 -1.272319   

    New(Sum of both columns )  
20                  -0.556727  
30                  -0.598033  
40                  -1.272319

In [219]:
df1.iloc[[1,2],] # it return all columns

B         C         D         E       new  \
30 -2.060141 -0.322417 -0.384054  1.133769 -0.598033   
40 -0.172428 -0.877858  0.042214  0.582815 -1.272319   

    New(Sum of both columns )  
30                  -0.598033  
40                  -1.272319

In [220]:
df1>0

B      C      D      E    new  New(Sum of both columns )
20   True  False   True  False  False                      False
30  False  False  False   True  False                      False
40  False  False   True   True  False                      False

In [221]:
df1.loc[[20,30]]>0

B      C      D      E    new  New(Sum of both columns )
20   True  False   True  False  False                      False
30  False  False  False   True  False                      False

In [222]:
df1[df1.loc[[20,30]]>0] # nan replca by False

B   C         D         E  new  New(Sum of both columns )
20  1.744812 NaN  0.319039       NaN  NaN                        NaN
30       NaN NaN       NaN  1.133769  NaN                        NaN
40       NaN NaN       NaN       NaN  NaN                        NaN

In [223]:
df>0

sd     we     er    we
23  False  False   True  True
3    True   True  False  True
45   True   True   True  True
34  False  False   True  True
45  False   True  False  True

In [227]:
np.matrix('45,4,3')

matrix([[45,  4,  3]])

In [228]:
np.array([1,2,3]) # this is a 

array([1, 2, 3])

In [235]:
t=np.array([1,2,34])

In [237]:
np.mat(t)

matrix([[ 1,  2, 34]])

In [239]:
mat=np.matrix('34,2,3;67,56,4;88,7,5;1,2,3')
mat

matrix([[34,  2,  3],
        [67, 56,  4],
        [88,  7,  5],
        [ 1,  2,  3]])

In [246]:
rt=np.array('2,3,4;5,4,3;')

In [247]:
rt

array('2,3,4;5,4,3;', dtype='<U12')

In [ ]:
df=pd.DataFrame(mat,columns_heading)

In [242]:
row_label=['A','b','c','d']
columns_heading=['Age','Height','Weight']

In [243]:
df=pd.DataFrame(mat,row_label,columns_heading)

In [244]:
df

Age  Height  Weight
A   34       2       3
b   67      56       4
c   88       7       5
d    1       2       3

In [248]:
df['Height']

A     2
b    56
c     7
d     2
Name: Height, dtype: int32

In [249]:
df['Height']<65

A    True
b    True
c    True
d    True
Name: Height, dtype: bool

In [250]:
df[df['Height']<65] # on whole data frame

Age  Height  Weight
A   34       2       3
b   67      56       4
c   88       7       5
d    1       2       3

In [375]:
df[df['Height']<56 & df['Age']>30 & df['Weight']>125]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [259]:
tt=df['Height']<56 #and df['Age']>30

In [261]:
tt1=df['Weight']>125

In [262]:
tt2=df['Age']>30

In [269]:
df[(tt) & (tt1) &(tt2)] # we can not use and or in pandas  module

Empty DataFrame
Columns: [Age, Height, Weight]
Index: []

In [270]:
df[(tt) | (tt1) &(tt2)]

Age  Height  Weight
A   34       2       3
c   88       7       5
d    1       2       3

In [276]:
df

index  Age  Height  Weight
0     A   34       2       3
1     b   67      56       4
2     c   88       7       5
3     d    1       2       3

In [277]:
df.reset_index() # for resetting the index # here we want to find out the deffault indexes

level_0 index  Age  Height  Weight
0        0     A   34       2       3
1        1     b   67      56       4
2        2     c   88       7       5
3        3     d    1       2       3

In [376]:
df.reset_index(drop=True) # for resetting the index # for dropping the previous data

level_0 index  Age  Height  Weight Professional
0        0     A   34       2       3      Student
1        1     b   67      56       4      Teacher
2        2     c   88       7       5       Docter
3        3     d    1       2       3        Norse

In [283]:
df

level_0 index  Age  Height  Weight
0        0     A   34       2       3
1        1     b   67      56       4
2        2     c   88       7       5
3        3     d    1       2       3

In [284]:
df

level_0 index  Age  Height  Weight
0        0     A   34       2       3
1        1     b   67      56       4
2        2     c   88       7       5
3        3     d    1       2       3

In [285]:
"Student Teacher Docter Norse".split() # it returns a list

['Student', 'Teacher', 'Docter', 'Norse']

In [286]:
df['Professional']="Student Teacher Docter Norse".split()

In [287]:
df

level_0 index  Age  Height  Weight Professional
0        0     A   34       2       3      Student
1        1     b   67      56       4      Teacher
2        2     c   88       7       5       Docter
3        3     d    1       2       3        Norse

In [292]:
df.set_index('Professional') #  now Professional columns wil be the index one

level_0 index  Age  Height  Weight
Professional                                    
Student             0     A   34       2       3
Teacher             1     b   67      56       4
Docter              2     c   88       7       5
Norse               3     d    1       2       3

# multiindexing

In [293]:
'-'*45

'---------------------------------------------'

In [294]:
'----'*45

'------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'

In [296]:
outside=['g1','g2','g3','g4']
inside=[1,2,3,4]
hier=list(zip(outside,inside))

In [300]:
hier_index=pd.MultiIndex.from_tuples(hier)

In [301]:
hier_index

MultiIndex([('g1', 1),
            ('g2', 2),
            ('g3', 3),
            ('g4', 4)],
           )

In [304]:
pd.DataFrame(data=np.round(rn(4,2)),index=hier_index,columns=['A','B'])

A    B
g1 1 -0.0  1.0
g2 2 -1.0 -0.0
g3 3 -1.0 -1.0
g4 4 -1.0 -0.0

In [307]:
l1=['A','A','A','B','B','B','C','C','C']
l2=[1,2,3,1,2,3,1,2,3]
l3=[1,3,5,4,5,6,7,8,9]

In [308]:
ind=list(zip(l1,l2,l3))

In [309]:
ind

[('A', 1, 1),
 ('A', 2, 3),
 ('A', 3, 5),
 ('B', 1, 4),
 ('B', 2, 5),
 ('B', 3, 6),
 ('C', 1, 7),
 ('C', 2, 8),
 ('C', 3, 9)]

In [320]:
ind=pd.MultiIndex.from_tuples(ind)

In [329]:
pd.DataFrame(data=np.round(rn(9,4)),index=ind,columns=[1,2,3,4])

1    2    3    4
A 1 1  1.0 -0.0  1.0  0.0
  2 3  1.0 -1.0  0.0  1.0
  3 5 -1.0 -0.0  0.0 -1.0
B 1 4  0.0  1.0 -1.0  0.0
  2 5 -1.0 -0.0 -2.0  1.0
  3 6  0.0 -0.0 -1.0  1.0
C 1 7  2.0 -2.0  1.0  2.0
  2 8  0.0 -1.0  1.0 -0.0
  3 9 -1.0 -1.0  1.0  1.0

In [330]:
dfcsv=pd.read_csv(r"C:\Users\asus\Internshala\variance.csv")

In [336]:
dfcsv.shape

(100, 4)

In [331]:
dfcsv

Student Overall Marks     Gender    Subject
0     Anish          9700       Male    English
1   Rishabh            83       Male    English
2      Ajay           NaN       Male    Physics
3   Abhinav            86       Male  Chemistry
4    Anurag            91       Male    English
..      ...           ...        ...        ...
95  Aaditya            77       Male  Chemistry
96    vivek          Male        NaN        NaN
97    Tisha             7     Female    English
98       73          Male    English        NaN
99   Ishita        Female  Chemistry        NaN

[100 rows x 4 columns]

In [334]:
dfcsv.dropna()

Student Overall Marks  Gender    Subject
0     Anish          9700    Male    English
1   Rishabh            83    Male    English
3   Abhinav            86    Male  Chemistry
4    Anurag            91    Male    English
6     Varun            83    Male  Chemistry
..      ...           ...     ...        ...
92     Dawn            73  Female    Physics
93    ankur            17    Male  Chemistry
94   Smriti             0  Female  Chemistry
95  Aaditya            77    Male  Chemistry
97    Tisha             7  Female    English

[87 rows x 4 columns]

In [335]:
dfcsv

Student Overall Marks     Gender    Subject
0     Anish          9700       Male    English
1   Rishabh            83       Male    English
2      Ajay           NaN       Male    Physics
3   Abhinav            86       Male  Chemistry
4    Anurag            91       Male    English
..      ...           ...        ...        ...
95  Aaditya            77       Male  Chemistry
96    vivek          Male        NaN        NaN
97    Tisha             7     Female    English
98       73          Male    English        NaN
99   Ishita        Female  Chemistry        NaN

[100 rows x 4 columns]

In [338]:
dfcsv.dropna(axis=1) # all columns deleted 

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

[100 rows x 0 columns]

In [341]:
# that number of non nan values or not
dfcsv.dropna(thresh=2)

Student Overall Marks     Gender    Subject
0     Anish          9700       Male    English
1   Rishabh            83       Male    English
2      Ajay           NaN       Male    Physics
3   Abhinav            86       Male  Chemistry
4    Anurag            91       Male    English
..      ...           ...        ...        ...
95  Aaditya            77       Male  Chemistry
96    vivek          Male        NaN        NaN
97    Tisha             7     Female    English
98       73          Male    English        NaN
99   Ishita        Female  Chemistry        NaN

[100 rows x 4 columns]

In [343]:
dfcsv.dropna(thresh=4) # 4 non nan value or not

Student Overall Marks  Gender    Subject
0     Anish          9700    Male    English
1   Rishabh            83    Male    English
3   Abhinav            86    Male  Chemistry
4    Anurag            91    Male    English
6     Varun            83    Male  Chemistry
..      ...           ...     ...        ...
92     Dawn            73  Female    Physics
93    ankur            17    Male  Chemistry
94   Smriti             0  Female  Chemistry
95  Aaditya            77    Male  Chemistry
97    Tisha             7  Female    English

[87 rows x 4 columns]

In [384]:
dfcsv.dropna(thresh=4,axis=0) # thresh it will drop that row in which non nan value is less then 4 

Student Overall Marks  Gender    Subject
0     Anish          9700    Male    English
1   Rishabh            83    Male    English
3   Abhinav            86    Male  Chemistry
4    Anurag            91    Male    English
6     Varun            83    Male  Chemistry
..      ...           ...     ...        ...
92     Dawn            73  Female    Physics
93    ankur            17    Male  Chemistry
94   Smriti             0  Female  Chemistry
95  Aaditya            77    Male  Chemistry
97    Tisha             7  Female    English

[87 rows x 4 columns]