In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as pn

In [2]:
df=pd.read_csv(r"C:\Users\asus\Downloads\advertising (1).csv")

In [3]:
df.head(30)

TV  Radio  Newspaper  Sales
0   230.1   37.8       69.2   22.1
1    44.5   39.3       45.1   10.4
2    17.2   45.9       69.3   12.0
3   151.5   41.3       58.5   16.5
4   180.8   10.8       58.4   17.9
5     8.7   48.9       75.0    7.2
6    57.5   32.8       23.5   11.8
7   120.2   19.6       11.6   13.2
8     8.6    2.1        1.0    4.8
9   199.8    2.6       21.2   15.6
10   66.1    5.8       24.2   12.6
11  214.7   24.0        4.0   17.4
12   23.8   35.1       65.9    9.2
13   97.5    7.6        7.2   13.7
14  204.1   32.9       46.0   19.0
15  195.4   47.7       52.9   22.4
16   67.8   36.6      114.0   12.5
17  281.4   39.6       55.8   24.4
18   69.2   20.5       18.3   11.3
19  147.3   23.9       19.1   14.6
20  218.4   27.7       53.4   18.0
21  237.4    5.1       23.5   17.5
22   13.2   15.9       49.6    5.6
23  228.3   16.9       26.2   20.5
24   62.3   12.6       18.3    9.7
25  262.9    3.5       19.5   17.0
26  142.9   29.3       12.6   15.0
27  240.1   16.7       22.9   20.9
28  248.8   27.1       22.9   18.9
29   70.6   16.0       40.8   10.5

In [4]:
df.isnull().sum() # there is no Null values here

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [5]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [6]:
a=ProfileReport(df)


In [7]:
a.to_widgets()

In [8]:
df['TV']

0      230.1
1       44.5
2       17.2
3      151.5
4      180.8
       ...  
195     38.2
196     94.2
197    177.0
198    283.6
199    232.1
Name: TV, Length: 200, dtype: float64

In [9]:
y=df['Sales']

In [10]:
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [11]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [12]:
x=df[['TV']]

In [13]:
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [14]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
lr=LinearRegression()

In [17]:
lr.fit(x,y) # find out the values of m and c 

LinearRegression()

In [18]:
lr.intercept_  #(this is the c)

6.974821488229891

In [19]:
lr.coef_ # this is the value of m

array([0.05546477])

In [20]:
lr.predict([[44.5]])

array([9.44300377])

In [21]:
lr.predict([[17.2]])

array([7.92881554])

In [22]:
l=[23,34,23,1,3,4,53,23,34,45,23]

In [23]:
for var in l:
    print(lr.predict([[var]])) # because one by one we are taking the values so that we are passing insize 2d array

[8.25051121]
[8.86062368]
[8.25051121]
[7.03028626]
[7.1412158]
[7.19668057]
[9.91445432]
[8.25051121]
[8.86062368]
[9.47073616]
[8.25051121]


In [24]:
pickle.dump(lr,open('model.sav','wb')) # saved model in model.sav file

In [25]:
lr.score(x,y) # accuracy of it 81.21%

0.8121757029987414

## Adjusted r^2

In [26]:
def adj_r2(x,y):
    r2=lr.score(x,y)
    n=x.shape[0]
    p=x.shape[1]
    adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [27]:
adj_r2(x,y)

0.811227095438129

In [28]:
#VIF(variance inflation factor)


In [29]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [30]:
x=df[['TV','Radio']]

In [31]:
y=df.Sales

In [32]:
lr1=LinearRegression()

In [33]:
lr1.fit(x,y)

LinearRegression()

In [34]:
lr1.score(x,y)

0.9025896186081139

In [35]:
lr1.intercept_

4.630879464097768

In [36]:
lr1.coef_

array([0.05444896, 0.10717457])

In [37]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [38]:
list1=[17.2,45.9]

In [39]:
lr1.predict([list1])

array([10.48671441])

In [40]:
lr1.score(x,y) # score is 90%

0.9025896186081139

In [41]:
lr3=LinearRegression()
x=df[['TV','Radio','Newspaper']]

In [42]:
y=df.Sales

In [43]:
lr3.fit(x,y)

LinearRegression()

In [44]:
lr3.intercept_

4.62512407880865

In [45]:
lr3.coef_

array([0.05444578, 0.10700123, 0.00033566])

In [46]:
lr3.score(x,y)

0.9025912899684558

In [47]:
import statsmodels.formula.api as smf

In [48]:
lrs=smf.ols(formula='Sales~TV',data=df).fit()# ordinary least square
lrs.summary()#  p means Radio is contribution 100%


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.812
Model:                            OLS   Adj. R-squared:                  0.811
Method:                 Least Squares   F-statistic:                     856.2
Date:                Mon, 04 Oct 2021   Prob (F-statistic):           7.93e-74
Time:                        09:31:58   Log-Likelihood:                -448.99
No. Observations:                 200   AIC:                             902.0
Df Residuals:                     198   BIC:                             908.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.9748      0.323     21.624      0.000       6.339       7.611
TV             0.0555      0.002     29.260      0.000       0.052       0.059
==============================================================================
Omnibus:                        0.013   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.993   Jarque-Bera (JB):                0.043
Skew:                          -0.018   Prob(JB):                        0.979
Kurtosis:                       2.938   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [49]:
lrs=smf.ols(formula='Sales~Radio',data=df).fit()# ordinary least square
lrs.summary() # p means Radio is contribution 100%


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.122
Model:                            OLS   Adj. R-squared:                  0.118
Method:                 Least Squares   F-statistic:                     27.57
Date:                Mon, 04 Oct 2021   Prob (F-statistic):           3.88e-07
Time:                        09:31:58   Log-Likelihood:                -603.18
No. Observations:                 200   AIC:                             1210.
Df Residuals:                     198   BIC:                             1217.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     12.2357      0.653     18.724      0.000      10.947      13.524
Radio          0.1244      0.024      5.251      0.000       0.078       0.171
==============================================================================
Omnibus:                       11.077   Durbin-Watson:                   2.018
Prob(Omnibus):                  0.004   Jarque-Bera (JB):                9.124
Skew:                          -0.433   Prob(JB):                       0.0104
Kurtosis:                       2.414   Cond. No.                         51.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [50]:
lrs=smf.ols(formula='Sales~Radio',data=df).fit()# ordinary least square
lrs.summary() # p means Radio is contribution 100%


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.122
Model:                            OLS   Adj. R-squared:                  0.118
Method:                 Least Squares   F-statistic:                     27.57
Date:                Mon, 04 Oct 2021   Prob (F-statistic):           3.88e-07
Time:                        09:31:59   Log-Likelihood:                -603.18
No. Observations:                 200   AIC:                             1210.
Df Residuals:                     198   BIC:                             1217.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     12.2357      0.653     18.724      0.000      10.947      13.524
Radio          0.1244      0.024      5.251      0.000       0.078       0.171
==============================================================================
Omnibus:                       11.077   Durbin-Watson:                   2.018
Prob(Omnibus):                  0.004   Jarque-Bera (JB):                9.124
Skew:                          -0.433   Prob(JB):                       0.0104
Kurtosis:                       2.414   Cond. No.                         51.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [51]:
lrs=smf.ols(formula="Sales~TV+Radio+Newspaper",data=df).fit() # ordinary least square
lrs.summary() # p means Radio is contribution 100%


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     605.4
Date:                Mon, 04 Oct 2021   Prob (F-statistic):           8.13e-99
Time:                        09:31:59   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             774.7
Df Residuals:                     196   BIC:                             787.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6251      0.308     15.041      0.000       4.019       5.232
TV             0.0544      0.001     39.592      0.000       0.052       0.057
Radio          0.1070      0.008     12.604      0.000       0.090       0.124
Newspaper      0.0003      0.006      0.058      0.954      -0.011       0.012
==============================================================================
Omnibus:                       16.081   Durbin-Watson:                   2.251
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.655
Skew:                          -0.431   Prob(JB):                     9.88e-07
Kurtosis:                       4.605   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Model2

In [52]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,Lasso,RidgeCV,LarsCV,ElasticNet,ElasticNetCV
from sklearn.model_selection import train_test_split
import statsmodels.api as smf
import matplotlib.pyplot as plt

In [53]:
import seaborn as sns

In [54]:
from pandas_profiling import ProfileReport

In [55]:
df1=pd.read_csv(r"C:\Users\asus\Downloads\Admission_Predict.csv")

In [56]:
df1.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [57]:
r=ProfileReport(df1)

In [58]:
r.to_widgets()

In [59]:
df1.isnull().sum() # we do not have nay null values
                    #if we have some missing then we can use fillna()
                    #method

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [60]:
df1.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000   
mean   200.500000  316.807500   107.410000           3.087500    3.400000   
std    115.614301   11.473646     6.069514           1.143728    1.006869   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    100.750000  308.000000   103.000000           2.000000    2.500000   
50%    200.500000  317.000000   107.000000           3.000000    3.500000   
75%    300.250000  325.000000   112.000000           4.000000    4.000000   
max    400.000000  340.000000   120.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     3.452500    8.598925    0.547500          0.724350  
std      0.898478    0.596317    0.498362          0.142609  
min      1.000000    6.800000    0.000000          0.340000  
25%      3.000000    8.170000    0.000000          0.640000  
50%      3.500000    8.610000    1.000000          0.730000  
75%      4.000000    9.062500    1.000000          0.830000  
max      5.000000    9.920000    1.000000          0.970000

In [61]:
df1.drop(columns='Serial No.',inplace=True)

In [62]:
df1.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [63]:
df1.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [64]:
y=df1['Chance of Admit ']
x=df1.drop(columns='Chance of Admit ',axis=1)

In [65]:
x.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0        337          118                  4  4.5   4.5  9.65         1
1        324          107                  4  4.0   4.5  8.87         1
2        316          104                  3  3.0   3.5  8.00         1
3        322          110                  3  3.5   2.5  8.67         1
4        314          103                  2  2.0   3.0  8.21         0

In [66]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
395    0.82
396    0.84
397    0.91
398    0.67
399    0.95
Name: Chance of Admit , Length: 400, dtype: float64

# transformation Scalling down the data

In [67]:
st_sc=StandardScaler()
arr=st_sc.fit_transform(x) # it gives the array we dont cange the meaning of dataset just scall doen the dataset


In [68]:
arr

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, ...,  0.05293342,
        -1.00563118,  0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.16732114,
         1.42900622,  0.90911166],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.61012728,
         0.30403584, -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  0.61012728,
         1.78160888,  0.90911166]])

In [69]:
df_=pd.DataFrame(arr,columns=col) # convert into dataframe

NameError: name 'col' is not defined

In [ ]:
col=x.columns

In [ ]:
df_.head()

In [ ]:
df_.describe()

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [ ]:
df3=pd.DataFrame()
df3['VIF']=[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

In [ ]:
df3

In [ ]:
df3['Feature']=x.columns

In [ ]:
df3

In [ ]:
arr

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(arr,y,test_size=.10,random_state=100)

In [ ]:
X_train.shape

In [ ]:
X_test.shape

In [ ]:
lr=LinearRegression()
lr.fit(X_train,y_train)

In [ ]:
lr.coef_ # -0.00094332 not contributing much

In [ ]:
lr.intercept_

In [ ]:
lr.score(X_test,y_test) # this is the score of the model keep in in minf the  dsasad

In [ ]:
data=[337,118,4,4.5,4.5,9.65,1]
data1=[322,110,3,3.5,2.5,8.67,1]

In [ ]:
lr.predict(st_sc.transform([data]))

In [ ]:
lr.predict(st_sc.transform([data1]))

In [ ]:
y

In [ ]:
x.columns

## Save the model

In [ ]:
pickle.dump(lr,open("Admin_pred.pickle","wb"))

In [ ]:
ls

In [ ]:
x

## Adjusted R^2

In [ ]:
def adj_r2(x,y):
    r2=lr.score(x,y)
    n=x.shape[0]
    p=x.shape[1]
    adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [ ]:
adj_r2(X_test,y_test)

## Lasso

In [ ]:
## control the overfitting Ridge Lasso and Elastic

In [ ]:
from sklearn.linear_model import LassoCV

In [ ]:
lassocv=LassoCV(alphas=None,cv=50,max_iter=1000,normalize=True)

In [ ]:
lassocv.fit(X_train,y_train) # Lasscocv for finding the alpha parameter

In [ ]:
lassocv.alpha_

In [ ]:
ls_mo=Lasso(alpha=lassocv.alpha_)
ls_mo.fit(X_train,y_train)

In [ ]:
ls_mo.score(X_test,y_test) # 85% the score of the model

## Ridge

In [ ]:
ridge=RidgeCV(alphas=np.random.uniform(0,10,50),cv=10,normalize=True)
ridge.fit(X_train,y_train)

In [ ]:
ridge.alpha_

In [ ]:
rig=Ridge(alpha=ridge.alpha_)

In [ ]:
rig.fit(X_train,y_train)

In [ ]:
rig.score(X_test,y_test)

## Elastic 

In [ ]:
elastic=ElasticNetCV(alphas=None,cv=10) # cv 5 and 10 not 50 or 100

In [ ]:
elastic.fit(X_train,y_train)

In [ ]:
elastic.alpha_

In [ ]:
elastic.l1_ratio_

In [ ]:
elastic_lr=ElasticNet(elastic.alpha_,l1_ratio=elastic.l1_ratio_)

In [ ]:
elastic_lr.fit(X_train,y_train)

In [ ]:
elastic_lr.score(X_train,y_train)

In [ ]:
elastic_lr.predict(st_sc.transform([data]))

In [ ]:
y

In [ ]:
pickle.dump('elastic_lr',open("Elastic_net_model.sav","wb"))