## import Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from pandas_profiling import ProfileReport

## Load dataset

In [2]:
df=pd.read_csv(r"C:\Users\asus\Downloads\Real estate.csv")

In [3]:
df.head()

No  X1 transaction date  X2 house age  ...  X5 latitude  X6 longitude  Y house price of unit area
0   1             2012.917          32.0  ...     24.98298     121.54024                        37.9
1   2             2012.917          19.5  ...     24.98034     121.53951                        42.2
2   3             2013.583          13.3  ...     24.98746     121.54391                        47.3
3   4             2013.500          13.3  ...     24.98746     121.54391                        54.8
4   5             2012.833           5.0  ...     24.97937     121.54245                        43.1

[5 rows x 8 columns]

In [4]:
pd.Categorical(df['X3 distance to the nearest MRT station'])

[84.87882, 306.59470, 561.98450, 561.98450, 390.56840, ..., 4082.01500, 90.45606, 390.96960, 104.81010, 90.45606]
Length: 414
Categories (259, float64): [23.38284, 49.66105, 56.47425, 57.58945, ..., 5512.038, 6306.153, 6396.283, 6488.021]

In [5]:
a=ProfileReport(df)


In [6]:
a.to_widgets()

In [8]:
df.head()

No  X1 transaction date  X2 house age  ...  X5 latitude  X6 longitude  Y house price of unit area
0   1             2012.917          32.0  ...     24.98298     121.54024                        37.9
1   2             2012.917          19.5  ...     24.98034     121.53951                        42.2
2   3             2013.583          13.3  ...     24.98746     121.54391                        47.3
3   4             2013.500          13.3  ...     24.98746     121.54391                        54.8
4   5             2012.833           5.0  ...     24.97937     121.54245                        43.1

[5 rows x 8 columns]

In [9]:
df.drop(columns='No',axis=1,inplace=True)

In [10]:
df.head()

X1 transaction date  X2 house age  ...  X6 longitude  Y house price of unit area
0             2012.917          32.0  ...     121.54024                        37.9
1             2012.917          19.5  ...     121.53951                        42.2
2             2013.583          13.3  ...     121.54391                        47.3
3             2013.500          13.3  ...     121.54391                        54.8
4             2012.833           5.0  ...     121.54245                        43.1

[5 rows x 7 columns]

In [11]:
df.drop("X1 transaction date",axis=1,inplace=True)

In [65]:
df.drop("X6 longitude",axis=1,inplace=True)

In [66]:
df.head()

X2 house age  X3 distance to the nearest MRT station  X4 number of convenience stores  X5 latitude
0      1.255628                               -0.792495                         2.007407     1.125430
1      0.157086                               -0.616612                         1.667503     0.912444
2     -0.387791                               -0.414015                         0.307885     1.486860
3     -0.387791                               -0.414015                         0.307885     1.486860
4     -1.117223                               -0.549997                         0.307885     0.834188

In [73]:
df.head()

X2 house age  X3 distance to the nearest MRT station  X4 number of convenience stores  X5 latitude
0      1.255628                               -0.792495                         2.007407     1.125430
1      0.157086                               -0.616612                         1.667503     0.912444
2     -0.387791                               -0.414015                         0.307885     1.486860
3     -0.387791                               -0.414015                         0.307885     1.486860
4     -1.117223                               -0.549997                         0.307885     0.834188

In [74]:
y

0      37.9
1      42.2
2      47.3
3      54.8
4      43.1
       ... 
409    15.4
410    50.0
411    40.6
412    52.5
413    63.9
Name: Y house price of unit area, Length: 414, dtype: float64

In [84]:
X=X.drop(columns='X6 longitude',axis=1,inplace=True)

## Scalling Down the dataset

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
st_sc=StandardScaler()

In [19]:
arr=st_sc.fit_transform(X)

In [20]:
df=pd.DataFrame(arr,columns=X.columns)

In [21]:
df.head()

X2 house age  X3 distance to the nearest MRT station  X4 number of convenience stores  X5 latitude  X6 longitude
0      1.255628                               -0.792495                         2.007407     1.125430      0.448762
1      0.157086                               -0.616612                         1.667503     0.912444      0.401139
2     -0.387791                               -0.414015                         0.307885     1.486860      0.688183
3     -0.387791                               -0.414015                         0.307885     1.486860      0.688183
4     -1.117223                               -0.549997                         0.307885     0.834188      0.592937

In [22]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [24]:
variance_inflation_factor=[variance_inflation_factor(arr,i) for i in range(5)]

In [26]:
col=pd.Series(X.columns)
pd.concat([pd.Series(variance_inflation_factor),col],axis=1)

0                                       1
0  1.014249                            X2 house age
1  4.282985  X3 distance to the nearest MRT station
2  1.613339         X4 number of convenience stores
3  1.599017                             X5 latitude
4  2.923881                            X6 longitude

In [27]:
#variance_inflation_factor is not greater than 10 or 9 so that 

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.10,random_state=100)

In [30]:
X_train.shape

(372, 5)

In [31]:
y_train.shape

(372,)

In [32]:
X_test.shape

(42, 5)

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [35]:
lr.coef_

array([-2.59877898e-01, -4.30002814e-03,  1.11566270e+00,  2.37658562e+02,
       -1.06968745e+01])

In [36]:
X.columns

Index(['X2 house age', 'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude'],
      dtype='object')

In [90]:
import statsmodels.formula.api as smf

In [92]:
y.name

'Y house price of unit area'

In [96]:
lrs=smf.ols(formula='Y house price of unit area ~ X2 house age',data=df).fit()
lrs.summary()

SyntaxError: invalid syntax (<unknown>, line 1)

In [37]:
lr.intercept_

-4591.346231517246

In [38]:
y

0      37.9
1      42.2
2      47.3
3      54.8
4      43.1
       ... 
409    15.4
410    50.0
411    40.6
412    52.5
413    63.9
Name: Y house price of unit area, Length: 414, dtype: float64

In [39]:
lr.score(X_test,y_test)

0.7428956953047674

In [40]:
X

X2 house age  X3 distance to the nearest MRT station  X4 number of convenience stores  X5 latitude  X6 longitude
0            32.0                                84.87882                               10     24.98298     121.54024
1            19.5                               306.59470                                9     24.98034     121.53951
2            13.3                               561.98450                                5     24.98746     121.54391
3            13.3                               561.98450                                5     24.98746     121.54391
4             5.0                               390.56840                                5     24.97937     121.54245
..            ...                                     ...                              ...          ...           ...
409          13.7                              4082.01500                                0     24.94155     121.50381
410           5.6                                90.45606                                9     24.97433     121.54310
411          18.8                               390.96960                                7     24.97923     121.53986
412           8.1                               104.81010                                5     24.96674     121.54067
413           6.5                                90.45606                                9     24.97433     121.54310

[414 rows x 5 columns]

In [52]:
data=[32.0,84.87882,10,24.98298,121.54024]
datas=st_sc.fit_transform([data])

In [53]:
datas

array([[0., 0., 0., 0., 0.]])

In [55]:
st_sc.transform([data])

array([[0., 0., 0., 0., 0.]])

In [56]:
data3=[32.0,84.87882,10,24.98298,121.54024]

In [57]:
st_sc.transform([data3])

array([[0., 0., 0., 0., 0.]])

In [60]:
dd=st_sc.transform([[13.3,561.98450,5,24.98746,121.54391]])

In [64]:
lr.predict(dd)

array([-4593.09094334])

In [62]:
y

0      37.9
1      42.2
2      47.3
3      54.8
4      43.1
       ... 
409    15.4
410    50.0
411    40.6
412    52.5
413    63.9
Name: Y house price of unit area, Length: 414, dtype: float64