In [1]:
import numpy as np

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,5],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [6]:
np.array([1,2,3,4,5],dtype=str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [7]:
np.asarray([1,2,3])

array([1, 2, 3])

In [9]:
type(np.matrix([5,6])) # matrixes

numpy.matrix

In [10]:
np.asnayarray() # matrix is a subclass of a array


AttributeError: module 'numpy' has no attribute 'asnayarray'

In [13]:
np.fromstring("234231",sep="3")

array([234231.])

In [14]:
np.fromstring("234231",sep="2")

array([234231.])

In [15]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [17]:
np.linspace(0,10,num=10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [19]:
np.linspace(1,10,num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.zeros(4) # zeros function

array([0., 0., 0., 0.])

In [23]:
np.zeros((4,4)) # 4 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
a4=np.zeros((2,2,3))

In [28]:
a4.shape

(2, 2, 3)

In [32]:
a4.ndim

3

In [33]:
a4.size

12

In [34]:
np.ones((3,4)) # create an array 3 , 4 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.ones((3,4))+3 # add 3 to all the element

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [36]:
np.ones((3,4))+10  # 

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [37]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [38]:
np.empty((3,4))

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [41]:
np.empty((4,6))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86921822e-306, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 9.34608432e-307, 1.86921007e-306,
        7.56596412e-307, 2.22520559e-306, 7.56599128e-307],
       [8.45559303e-307, 8.06613040e-308, 6.89810244e-307,
        1.22387550e-307, 2.22522596e-306, 9.79103797e-307]])

In [42]:
np.empty((3,6))

array([[1.17919460e-311, 5.18768928e-322, 0.00000000e+000,
        0.00000000e+000, 1.33511018e-306, 1.15998412e-028],
       [2.44171989e+232, 8.00801729e+159, 6.60953820e-072,
        1.04987740e-153, 7.80437046e-120, 1.05773739e-153],
       [6.29916830e-019, 4.56295599e-144, 2.86530729e+161,
        8.93176633e+271, 4.98131536e+151, 1.78820115e-047]])

In [44]:
np.eye(4) # identity matrix diagonal 1 and all 0 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
np.arange(16).reshape(1,16).shape

(1, 16)

In [51]:
np.arange(16).reshape(16,1).shape

(16, 1)

In [52]:
np.arange(16).reshape(2,2,4) # 3 d array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [56]:
np.arange(16).reshape(3,3,3) # it will give an error

ValueError: cannot reshape array of size 16 into shape (3,3,3)

In [58]:
np.arange(16).reshape(2,-1) # it will work with any negative numnber

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [65]:
from numpy.random import randint

In [66]:
np.arange(16).reshape(4,-132,2) # it will automatically able to sense about the columns

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [68]:
np.random.rand(4,3) # uniform distribution  values between  0-1

array([[0.50896032, 0.89171558, 0.58763325],
       [0.80997084, 0.10889703, 0.6845955 ],
       [0.69068774, 0.76662415, 0.4523562 ],
       [0.35592921, 0.5788375 , 0.36844639]])

In [69]:
np.random.randn(4,5) # this is  standard normal distribution # sd=1, mean =0

array([[-1.10061761, -0.15626814,  0.65776996, -1.95357852,  0.04975519],
       [-0.11510104,  0.42236662,  1.23355304,  0.34363027, -1.50671979],
       [-0.05993611,  0.35609482, -0.61391519, -0.50574631, -0.43918168],
       [ 0.15091124,  1.14809032, -1.08246476, -1.90053085, -0.86181251]])

In [72]:
np.random.randint(4,7,(4,5))

array([[5, 6, 4, 5, 5],
       [5, 4, 6, 5, 5],
       [5, 6, 4, 4, 6],
       [5, 6, 5, 4, 5]])

In [75]:
np.random.randint(1,3,(3,4)) # every time it will give different values

array([[2, 2, 2, 1],
       [1, 2, 1, 1],
       [1, 2, 2, 2]])

In [80]:
np.random.seed(45) # fix a ranond number any number we can pass
np.random.randint(1,3,(3,4))

array([[2, 1, 2, 1],
       [1, 2, 2, 2],
       [2, 1, 2, 1]])

In [82]:
a5=np.random.randint(2,6,(3,4))

In [83]:
a5

array([[4, 2, 2, 2],
       [3, 4, 2, 4],
       [4, 4, 2, 4]])

In [84]:
np.sort(a5) # across rows only menas row wise sorting here

array([[2, 2, 2, 4],
       [2, 3, 4, 4],
       [2, 4, 4, 4]])

In [86]:
np.sort(a5,axis=1) # column wise sorting operation

array([[2, 2, 2, 4],
       [2, 3, 4, 4],
       [2, 4, 4, 4]])

In [87]:
a5

array([[4, 2, 2, 2],
       [3, 4, 2, 4],
       [4, 4, 2, 4]])

In [89]:
a5=np.random.randint(2,14,(3,4))

In [90]:
a5

array([[13, 13, 12,  8],
       [ 2,  6, 11, 10],
       [ 2, 11,  4,  8]])

In [91]:
np.sort(a5) # row wise sorting

array([[ 8, 12, 13, 13],
       [ 2,  6, 10, 11],
       [ 2,  4,  8, 11]])

In [92]:
np.sort(a5,axis=0) 

array([[ 2,  6,  4,  8],
       [ 2, 11, 11,  8],
       [13, 13, 12, 10]])

In [94]:
np.sort(a5,axis=1,kind="mergesort") 

array([[ 8, 12, 13, 13],
       [ 2,  6, 10, 11],
       [ 2,  4,  8, 11]])

In [97]:
a5.max() # maximum values retuens from the array

13

In [100]:
a5[1,2] # this is also a way for subscript

11

In [101]:
a5[1][2] # subscript we can use

11

In [103]:
a5

array([[13, 13, 12,  8],
       [ 2,  6, 11, 10],
       [ 2, 11,  4,  8]])

In [102]:
a5[1:,2:]

array([[11, 10],
       [ 4,  8]])

In [104]:
a5[2::2]

array([[ 2, 11,  4,  8]])

In [108]:
a7=np.array(np.arange(16).reshape(4,4))

In [109]:
a6=np.array(np.random.randint(1,5,(4,4)))

In [110]:
a6

array([[1, 1, 4, 3],
       [1, 4, 4, 1],
       [2, 4, 2, 2],
       [4, 4, 4, 1]])

In [111]:
a5/0 # in

<ipython-input-111-bdcb42fa6494>:1: RuntimeWarning: divide by zero encountered in true_divide
  a5/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [112]:
a6

array([[1, 1, 4, 3],
       [1, 4, 4, 1],
       [2, 4, 2, 2],
       [4, 4, 4, 1]])

In [113]:
a7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
a6*a7 # element wise multiplication operation

array([[ 0,  1,  8,  9],
       [ 4, 20, 24,  7],
       [16, 36, 20, 22],
       [48, 52, 56, 15]])

In [115]:
a6/a7

<ipython-input-115-8b5b7a5cd6c3>:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/a7


array([[       inf, 1.        , 2.        , 1.        ],
       [0.25      , 0.8       , 0.66666667, 0.14285714],
       [0.25      , 0.44444444, 0.2       , 0.18181818],
       [0.33333333, 0.30769231, 0.28571429, 0.06666667]])

In [116]:
a6.dot(a7) # matrix

array([[72, 81, 90, 99],
       [60, 70, 80, 90],
       [56, 66, 76, 86],
       [60, 73, 86, 99]])

In [118]:
a6@a7 # this is also a way

array([[72, 81, 90, 99],
       [60, 70, 80, 90],
       [56, 66, 76, 86],
       [60, 73, 86, 99]])

In [119]:
a6

array([[1, 1, 4, 3],
       [1, 4, 4, 1],
       [2, 4, 2, 2],
       [4, 4, 4, 1]])

In [121]:
a6.T # transpose of matrix

array([[1, 1, 2, 4],
       [1, 4, 4, 4],
       [4, 4, 2, 4],
       [3, 1, 2, 1]])

In [122]:
a7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [123]:
a7**2 # square of every element

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]], dtype=int32)

In [124]:
a7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
np.empty((3,2)) # 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])